version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8  # Replace with your base image

jobs:
  hello-world:
    executor: default
    steps:
      - run:
          name: Print Hello World
          command: echo "Hello, World!"

  install-sonar-scanner:
    executor: default
    steps:
      - checkout  # Checkout your code
      - run:
          name: Install Sonar Scanner
          command: |
            curl -sSLo sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip"
            unzip sonar-scanner.zip
            export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
            echo 'export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin' >> $BASH_ENV

  run-sonar-scanner:
    executor: default
    steps:
      - checkout  # Checkout your code
      - run:
          name: Run Sonar Scanner
          command: |
            source $BASH_ENV  # Load the updated PATH
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - hello-world  # Run the Hello World job
      - install-sonar-scanner:
          requires:
            - hello-world  # Ensure Hello World runs before this job
      - run-sonar-scanner:
          requires:
            - install-sonar-scanner  # Ensure this runs after the Sonar Scanner installation
