name: Build APK and AAB

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node 20 compatibility

      - name: Set up JDK
        uses: actions/setup-java@v3  # Updated to v3 for Node 20 compatibility
        with:
          java-version: '11'

      - name: Change permissions of gradlew
        run: sudo chmod 755 ./gradlew

      - name: Build APK and AAB
        run: ./gradlew assembleDebug assembleRelease