name: Build APK and AAB

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node 20 compatibility

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'  # or 'temurin' depending on your preference

      - name: Give execute permissions to gradlew
        run: |
          sudo chmod 755 ./gradlew
          ls -l ./gradlew
          id -u
          id -gn

      - name: Run tests
        run: ./gradlew test

      - name: Build gradle project
        run: ./gradlew build

      - name: Create APK Debug
        run: ./gradlew assembleDebug

      - name: Create APK Release
        run: ./gradlew assembleRelease

      - name: Create Bundle AAB Release
        run: ./gradlew :app:bundleRelease

      - name: Upload Artifact Build
        uses: actions/upload-artifact@v3
        with:
          name: APK(s) release generated
          path: app/build/outputs/apk/release/

      - name: Upload AAB (App Bundle) Release
        uses: actions/upload-artifact@v3
        with:
          name: App bundle(s) AAB release generated
          path: app/build/outputs/bundle/release/